fix: Add set -e to create_migrations and update comment.

diff --git a/util/create_migrations b/util/create_migrations
--- a/util/create_migrations
+++ b/util/create_migrations
@@ -7,6 +7,9 @@ if [ ! -f util/.serverpod_util_root ]; then
     exit 1
 fi
 
+# Makes script exit on first non-zero error code
+set -e
+
 . "util/all_packages"
 
 BASE=`pwd`
