chore: Make it possible to configure sleep and start with named input parameters.

diff --git a/util/publish_all b/util/publish_all
--- a/util/publish_all
+++ b/util/publish_all
@@ -21,13 +21,45 @@ cd $CLI_DIR
 dart pub get
 cd $BASE
 
+# Parse command line arguments
 PCOUNT_START_DEFAULT=0
-PCOUNT_START="${1:-$PCOUNT_START_DEFAULT}"
+SLEEP_TIME_DEFAULT=1
+PCOUNT_START=$PCOUNT_START_DEFAULT
+SLEEP_TIME=$SLEEP_TIME_DEFAULT
+
+while [[ $# -gt 0 ]]; do
+  case $1 in
+    --start)
+      if [[ -z "$2" ]]; then
+        echo "Error: --start requires a value"
+        echo "Usage: $0 [--start N] [--sleep N]"
+        exit 1
+      fi
+      PCOUNT_START="$2"
+      shift 2
+      ;;
+    --sleep)
+      if [[ -z "$2" ]]; then
+        echo "Error: --sleep requires a value"
+        echo "Usage: $0 [--start N] [--sleep N]"
+        exit 1
+      fi
+      SLEEP_TIME="$2"
+      shift 2
+      ;;
+    *)
+      echo "Unknown option: $1"
+      echo "Usage: $0 [--start N] [--sleep N]"
+      exit 1
+      ;;
+  esac
+done
 
 echo "### START PUBLISHING"
 
 echo "Base directory $BASE"
 echo "Start at package $PCOUNT_START"
+echo "Sleep time between packages: $SLEEP_TIME seconds"
 
 VERSION=`cat SERVERPOD_VERSION`
 DART_VERSION=`cat DART_VERSION`
@@ -107,7 +139,7 @@ while read PACKAGE <&3; do
       echo ""
       echo "### PUBLISH FAILED: $PCOUNT"
       echo "Fix issues, then resume by running"
-      echo "util/publish_all $PCOUNT"
+      echo "util/publish_all --start $PCOUNT --sleep $SLEEP_TIME"
       echo ""
       echo ""
       break
@@ -115,7 +147,7 @@ while read PACKAGE <&3; do
 
     # Give pub.dev a chance to catch up between each package deployment
     echo ""
-    sleep 1
+    sleep $SLEEP_TIME
   else
     echo "### SKIPPING PACKAGE: $PCOUNT"
     echo "$PACKAGE"
