Adds dart analyze to tests

diff --git a/util/run_tests b/util/run_tests
--- a/util/run_tests
+++ b/util/run_tests
@@ -1,5 +1,38 @@
 #!/bin/sh
 
-cd tests/docker
+if [ ! -f tests/docker/docker-compose.yml ]; then
+    echo "Run this script from the root of the Serverpod repository"
+    echo "I.e. util/run_tests"
+    exit 1
+fi
 
-docker-compose up --abort-on-container-exit --exit-code-from tests --build
+# Makes script exit on first non-zero error code
+set -e
+
+echo "### Checking dart format"
+dart format -o none --set-exit-if-changed .
+echo ""
+
+echo "### Running dart analyze"
+dart analyze packages/serverpod
+dart analyze packages/serverpod_client
+dart analyze packages/serverpod_relic
+dart analyze packages/serverpod_serialization
+dart analyze packages/serverpod_service_client
+dart analyze packages/serverpod_shared
+
+dart analyze tests/serverpod_test_server
+dart analyze tests/serverpod_test_client
+dart analyze tests/serverpod_test_module/serverpod_test_module_server
+dart analyze tests/serverpod_test_module/serverpod_test_module_client
+
+# dart analyze modules/serverpod_auth/serverpod_auth_server
+# dart analyze modules/serverpod_auth/serverpod_auth_client
+# dart analyze modules/serverpod_auth/serverpod_auth_apple_flutter
+# dart analyze modules/serverpod_auth/serverpod_auth_google_flutter
+# dart analyze modules/serverpod_auth/serverpod_auth_shared_flutter
+
+# dart analyze integrations/serverpod_cloud_storage_s3
+
+echo "### Running unit tests"
+util/run_tests_single_server
