fix(review): By default run module integration test concurrently Allow exceptions with custom test tag

diff --git a/.github/workflows/dart-tests.yaml b/.github/workflows/dart-tests.yaml
--- a/.github/workflows/dart-tests.yaml
+++ b/.github/workflows/dart-tests.yaml
@@ -258,8 +258,13 @@ jobs:
           ./wait-for-it.sh localhost:9090 -t 60 -- echo "### Postgres is UP at :9090"
           ./wait-for-it.sh localhost:9091 -t 60 -- echo "### Redis is UP at :9091"
         working-directory: tests/docker/tests_integration
-      - name: Run integration tests
-        run: dart test -t integration --concurrency=1 --reporter=failures-only
+      - name: Run integration tests (concurrently)
+        run: dart test -t integration -x concurrency_one --reporter=failures-only
+        working-directory: ${{ matrix.module }}
+      - name: Run integration tests (sequentially)
+        if: always()
+        # Exit code `79` means that no tests were found for the tags
+        run: dart test -t integration -t concurrency_one --concurrency=1 --reporter=failures-only || [ $? -eq 79 ]
         working-directory: ${{ matrix.module }}
       - name: Stop containers
         if: always()
